# Generated by Django 3.1.4 on 2021-01-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setup2',
            old_name='bemerkug',
            new_name='bemerkung',
        ),
    ]
