# Generated by Django 3.1.4 on 2021-01-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_auto_20210114_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffid', models.AutoField(db_column='staffId', primary_key=True, serialize=False)),
                ('staffname', models.CharField(blank=True, db_column='staffName', max_length=30, null=True)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
    ]
