# Generated by Django 3.1.4 on 2021-03-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup2',
            name='dokumenttyp',
            field=models.CharField(blank=True, choices=[('Allg. Schriftstück', 'Allg. Schriftstück'), ('Bericht', 'Bericht'), ('Buch', 'Buch'), ('Datenträger', 'Datenträger'), ('Dia', 'Dia'), ('Diplomarbeit', 'Diplomarbeit'), ('Dissertation', 'Dissertation'), ('Dokumente', 'Dokumente'), ('Film', 'Film'), ('Folie', 'Folie'), ('Studienarbeit(exp.)', 'Studienarbeit(exp.)'), ('Studienarbeit(konstr.)', 'Studienarbeit(konstr.)'), ('Zeitschrift', 'Zeitschrift')], db_column='Dokumenttyp', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='setup2',
            name='medium',
            field=models.CharField(blank=True, choices=[('CD-Rom', 'CD-Rom'), ('DAT', 'DAT'), ('Diskette', 'Diskette'), ('Magnetband', 'Magnetband'), ('MO-Disk', 'MO-Disk'), ('Wechselplatte', 'Wechselplatte'), ('Flash-Speicher', 'Flash-Speicher')], db_column='Medium', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='setup2',
            name='sprache',
            field=models.CharField(blank=True, choices=[('Chinesisch', 'Chinesisch'), ('Deutsch', 'Deutsch'), ('Englisch', 'Englisch'), ('Französisch', 'Französisch'), ('Italienisch', 'Italienisch'), ('Japanisch', 'Japanisch'), ('Polnisch', 'Polnisch'), ('Russisch', 'Russisch'), ('Spanisch', 'Spanisch'), ('Weitere...', 'Weitere...')], db_column='Sprache', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='setup2',
            name='standort',
            field=models.CharField(blank=True, choices=[('Archive', 'Archive'), ('Bibliothek', 'Bibliothek'), ('Speicher', 'Speicher')], db_column='Standort', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='setup2',
            name='zustand',
            field=models.CharField(blank=True, choices=[('fehlt', 'fehlt'), ('in Ordnung', 'in Ordnung'), ('in Reparatur', 'in Reparatur')], db_column='Zustand', max_length=50, null=True),
        ),
    ]
