# Generated by Django 3.1.4 on 2021-03-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_auto_20210303_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup2',
            name='dk_etikett_andere',
            field=models.CharField(blank=True, db_column='DK_Etikett_Andere', max_length=50, null=True),
        ),
    ]
