# Generated by Django 3.1.4 on 2021-03-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0006_auto_20210306_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup2',
            name='titel',
            field=models.CharField(blank=True, db_column='Titel', max_length=500, null=True),
        ),
    ]
