# Generated by Django 3.1.4 on 2021-04-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0007_auto_20210308_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup2',
            name='medium',
            field=models.CharField(blank=True, choices=[('CD-Rom', 'CD-Rom'), ('DAT', 'DAT'), ('Diskette', 'Diskette'), ('Magnetband', 'Magnetband'), ('MO-Disk', 'MO-Disk'), ('Wechselplatte', 'Wechselplatte'), ('USB-Stick', 'USB-Stick')], db_column='Medium', max_length=50, null=True),
        ),
    ]
