# Generated by Django 3.1.4 on 2021-06-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0008_auto_20210417_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
