# Generated by Django 3.1.4 on 2021-08-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0009_delete_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup2',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'On loan'), ('a', 'Available'), ('m', 'Maintenance')], default='m', help_text='Verfügbarkeit', max_length=1),
        ),
    ]
