# Generated by Django 3.1.4 on 2021-09-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0010_setup2_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup2',
            name='status',
        ),
    ]
